# Generated by Django 5.0 on 2025-04-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
